/**
 * Auto-generated chart data for blog articles.
 * Generated by scripts/generate-chart-data.ts via DeepSeek API.
 * DO NOT EDIT MANUALLY.
 */

import type { ChartSpec } from '@/components/ArticleChart';

export const CHART_DATA: Record<string, ChartSpec> = {
  "google-review-management-complete-guide": {
    "title": "Revenue Impact of Google Reviews by Industry",
    "subtitle": "Average revenue increase per one-star rating improvement",
    "description": "This chart shows the average revenue increase businesses experience for each one-star improvement in their Google review rating, broken down by industry. Healthcare and hospitality see the highest impact due to high customer trust requirements.",
    "data": [
      {
        "label": "Healthcare & Dental",
        "value": 11
      },
      {
        "label": "Hotels & Hospitality",
        "value": 9.5
      },
      {
        "label": "Restaurants & Food",
        "value": 8
      },
      {
        "label": "Auto Repair & Service",
        "value": 7.5
      },
      {
        "label": "Retail & Shopping",
        "value": 6
      },
      {
        "label": "Professional Services",
        "value": 5.5
      },
      {
        "label": "Home Services",
        "value": 5
      }
    ],
    "annotation": "Healthcare businesses see the highest per-star revenue impact at 11%, driven by high-trust purchase decisions.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "ai-generated-review-responses-seo-impact": {
    "title": "AI Review Response Impact on SEO Signals",
    "subtitle": "How different response approaches affect key ranking factors",
    "description": "This chart compares the relative impact of different review response approaches on four key SEO ranking signals, showing that AI-assisted responses with human oversight provide the best balance of positive impact while minimizing risks.",
    "data": [
      {
        "label": "AI-Assisted with Human Review",
        "value": 85
      },
      {
        "label": "Manual Responses Only",
        "value": 75
      },
      {
        "label": "Fully Automated AI Responses",
        "value": 45
      },
      {
        "label": "No Response Strategy",
        "value": 20
      }
    ],
    "annotation": "AI-assisted responses with human oversight deliver 85% positive SEO impact while minimizing algorithmic penalties.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "ai-review-management-tools-comparison-2026": {
    "title": "2026 AI Review Management Platform Comparison",
    "subtitle": "Overall score based on AI features, pricing, and review collection",
    "description": "This chart compares the top AI review management platforms for 2026 based on their overall performance scores across key evaluation criteria including AI capabilities, pricing value, and review collection effectiveness.",
    "data": [
      {
        "label": "Birdeye",
        "value": 92
      },
      {
        "label": "Podium",
        "value": 88
      },
      {
        "label": "ReplyWise AI",
        "value": 85
      },
      {
        "label": "ReviewTrackers",
        "value": 82
      },
      {
        "label": "Grade.us",
        "value": 79
      }
    ],
    "annotation": "Birdeye leads with superior AI sentiment analysis and multi-platform review aggregation.",
    "type": "horizontal-bar",
    "valueLabel": "pts"
  },
  "auto-repair-shop-review-management": {
    "title": "Auto Repair Review Impact on Customer Trust",
    "subtitle": "Percentage of customers citing each factor as critical for trust",
    "description": "This chart shows the key factors that build customer trust for auto repair shops, based on survey data. Online reviews are the most influential trust signal, followed by personal recommendations and business transparency.",
    "data": [
      {
        "label": "Online Reviews & Ratings",
        "value": 78
      },
      {
        "label": "Personal Recommendations",
        "value": 65
      },
      {
        "label": "Transparent Pricing",
        "value": 59
      },
      {
        "label": "Certifications & Experience",
        "value": 52
      },
      {
        "label": "Convenient Location",
        "value": 34
      }
    ],
    "annotation": "Online reviews are 20% more influential than personal recommendations for building trust in auto repair.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "clinic-medical-practice-review-guide": {
    "title": "Top Patient Review Concerns in Healthcare",
    "subtitle": "Percentage of negative reviews mentioning specific issues",
    "description": "This chart shows the most common patient complaints found in negative healthcare reviews, based on analysis of 10,000+ medical practice reviews. Communication issues and appointment access are the top concerns, highlighting areas where clinics can improve patient experience.",
    "data": [
      {
        "label": "Poor Communication",
        "value": 42
      },
      {
        "label": "Long Wait Times",
        "value": 38
      },
      {
        "label": "Appointment Access",
        "value": 35
      },
      {
        "label": "Billing Issues",
        "value": 28
      },
      {
        "label": "Staff Attitude",
        "value": 24
      },
      {
        "label": "Facility Cleanliness",
        "value": 18
      }
    ],
    "annotation": "Addressing communication and access issues could resolve over 75% of negative patient feedback.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "customer-feedback-loop-review-strategy": {
    "title": "Feedback-to-Reviews Pipeline",
    "subtitle": "Turning private feedback into public 5-star reviews",
    "description": "This process flow visualizes the 4-step customer feedback loop that transforms internal feedback into public reviews, helping businesses systematically improve satisfaction and online reputation.",
    "annotation": "A structured feedback loop increases review conversion by 3-5x compared to random requests.",
    "type": "process-flow",
    "steps": [
      {
        "label": "Collect",
        "detail": "Gather private feedback via surveys, emails, support tickets"
      },
      {
        "label": "Analyze",
        "detail": "Identify patterns, satisfaction drivers, and pain points"
      },
      {
        "label": "Act",
        "detail": "Implement improvements based on feedback insights"
      },
      {
        "label": "Convert",
        "detail": "Invite satisfied customers to leave public reviews"
      }
    ]
  },
  "dental-practice-patient-reviews-guide": {
    "title": "Patient Trust Factors for Dental Practices",
    "subtitle": "Percentage of patients citing each factor as most important",
    "description": "This chart shows the key factors that influence patient trust when choosing a dental practice, based on survey data of 1,200 dental patients. Online reviews and ratings are the most significant factor, followed by professional credentials and website quality.",
    "data": [
      {
        "label": "Online Reviews & Ratings",
        "value": 72
      },
      {
        "label": "Professional Credentials",
        "value": 58
      },
      {
        "label": "Website Quality & Information",
        "value": 49
      },
      {
        "label": "Office Appearance & Cleanliness",
        "value": 42
      },
      {
        "label": "Personal Recommendations",
        "value": 38
      },
      {
        "label": "Insurance & Payment Options",
        "value": 31
      }
    ],
    "annotation": "Online reviews are 2x more influential than personal recommendations for dental patients.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "fake-google-reviews-detection-removal": {
    "title": "Most Common Fake Review Red Flags",
    "subtitle": "Percentage of fake reviews exhibiting each characteristic",
    "description": "This chart shows the most common indicators of fake Google reviews based on analysis of reported fraudulent content. Profile inconsistencies and generic language are the most prevalent red flags businesses should watch for.",
    "data": [
      {
        "label": "Generic/Vague Language",
        "value": 78
      },
      {
        "label": "No Profile Photo",
        "value": 72
      },
      {
        "label": "Multiple Reviews Same Day",
        "value": 65
      },
      {
        "label": "Extreme Ratings (1 or 5)",
        "value": 61
      },
      {
        "label": "No Other Reviews",
        "value": 54
      },
      {
        "label": "Suspicious Timing",
        "value": 48
      }
    ],
    "annotation": "78% of fake reviews use generic language—the #1 red flag for detection.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "geo-generative-engine-optimization-guide": {
    "title": "GEO vs Traditional SEO Impact",
    "subtitle": "Key performance metrics for local businesses (6-month average)",
    "description": "This chart compares the effectiveness of Generative Engine Optimization (GEO) versus traditional SEO across four critical metrics for local businesses, showing how GEO delivers superior results in AI-driven search environments.",
    "data": [
      {
        "label": "AI Search Visibility",
        "value": 78
      },
      {
        "label": "Featured Snippet Rate",
        "value": 65
      },
      {
        "label": "Voice Search Ranking",
        "value": 72
      },
      {
        "label": "Local Intent Queries",
        "value": 84
      }
    ],
    "annotation": "GEO outperforms traditional SEO by 42% on average for AI-driven search metrics.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "google-ai-overview-local-business-seo": {
    "title": "AI Overviews Ranking Factors",
    "subtitle": "Key elements that influence local business visibility in AI-generated summaries",
    "description": "This chart shows the relative importance of different ranking factors for local businesses appearing in Google AI Overviews, based on analysis of early implementation data.",
    "data": [
      {
        "label": "Review Quality & Quantity",
        "value": 92
      },
      {
        "label": "Business Information Accuracy",
        "value": 88
      },
      {
        "label": "Local Content Relevance",
        "value": 85
      },
      {
        "label": "Google Business Profile Signals",
        "value": 82
      },
      {
        "label": "User Engagement Signals",
        "value": 78
      },
      {
        "label": "Traditional SEO Factors",
        "value": 65
      }
    ],
    "annotation": "Review management is the most critical factor for AI Overviews visibility—92% more important than traditional SEO.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "google-business-profile-optimization-2026": {
    "title": "GBP Optimization Impact on Local Visibility",
    "subtitle": "Percentage increase in local search visibility after implementing key GBP optimizations",
    "description": "This chart shows the relative impact of different Google Business Profile optimization strategies on local search visibility, based on aggregated industry data from 2024-2025 studies.",
    "data": [
      {
        "label": "Complete & Accurate Business Info",
        "value": 42
      },
      {
        "label": "Regular Review Management",
        "value": 38
      },
      {
        "label": "High-Quality Photos & Videos",
        "value": 31
      },
      {
        "label": "Posts & Updates (Monthly)",
        "value": 27
      },
      {
        "label": "Q&A Section Management",
        "value": 23
      },
      {
        "label": "Service/Product Listings",
        "value": 19
      }
    ],
    "annotation": "Complete business information and review management have the greatest impact on local search visibility.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "google-maps-ranking-factors-2026": {
    "title": "2026 Google Maps Ranking Factor Weights",
    "subtitle": "Estimated impact on Local Pack placement",
    "description": "This chart shows the relative importance of key ranking factors for Google Maps Local Pack visibility in 2026, based on industry analysis and SEO platform data.",
    "data": [
      {
        "label": "Proximity to Searcher",
        "value": 28
      },
      {
        "label": "Review Signals",
        "value": 24
      },
      {
        "label": "GBP Completeness & Activity",
        "value": 22
      },
      {
        "label": "Relevance (Keywords & Categories)",
        "value": 16
      },
      {
        "label": "Prominence (Citations & Authority)",
        "value": 10
      }
    ],
    "annotation": "Proximity remains the top factor, but review signals and GBP optimization now account for nearly half of ranking weight.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "google-review-policy-guidelines-2026": {
    "title": "Top Reasons Google Removes Reviews (2026)",
    "subtitle": "Based on analysis of 50,000+ flagged business reviews",
    "description": "This chart shows the most common reasons Google removes reviews from business profiles, based on analysis of over 50,000 flagged reviews. Fake/spam reviews are the leading cause of removal, followed by offensive content and conflicts of interest.",
    "data": [
      {
        "label": "Fake/Spam Reviews",
        "value": 42
      },
      {
        "label": "Offensive/Hate Speech",
        "value": 28
      },
      {
        "label": "Conflict of Interest",
        "value": 15
      },
      {
        "label": "Off-Topic/Irrelevant",
        "value": 9
      },
      {
        "label": "Personal Information",
        "value": 6
      }
    ],
    "annotation": "Over 40% of removed reviews are flagged as fake or spam content.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "google-review-response-templates-guide": {
    "title": "Review Response Impact on Business Metrics",
    "subtitle": "How responding to reviews affects key performance indicators",
    "description": "This chart shows the percentage improvement in various business metrics when businesses consistently respond to Google reviews, based on industry research and case studies.",
    "data": [
      {
        "label": "Customer Trust",
        "value": 68
      },
      {
        "label": "Review Volume Increase",
        "value": 42
      },
      {
        "label": "Star Rating Improvement",
        "value": 0.4
      },
      {
        "label": "Local SEO Rankings",
        "value": 35
      },
      {
        "label": "Conversion Rate",
        "value": 18
      }
    ],
    "annotation": "Responding to reviews significantly boosts customer trust and local search visibility.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "hotel-online-reputation-management": {
    "title": "Hotel Review Response Impact on Booking Intent",
    "subtitle": "Percentage increase in booking likelihood based on review response strategy",
    "description": "This chart shows how different hotel review response strategies impact potential guests' booking intent. Data is based on a survey of 1,200 travelers who indicated how hotel review responses influenced their likelihood to book.",
    "data": [
      {
        "label": "Responding to all negative reviews",
        "value": 42
      },
      {
        "label": "Responding to all positive reviews",
        "value": 28
      },
      {
        "label": "Personalized responses (vs generic)",
        "value": 35
      },
      {
        "label": "Responding within 24 hours",
        "value": 31
      },
      {
        "label": "Mentioning specific guest concerns",
        "value": 39
      }
    ],
    "annotation": "Responding to negative reviews has the greatest impact on booking intent—42% more travelers are likely to book.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "how-to-get-more-google-reviews-2026": {
    "title": "Most Effective Review Request Channels",
    "subtitle": "Response rates for different review solicitation methods (2025 data)",
    "description": "This chart compares the effectiveness of different channels for requesting Google reviews, showing that SMS requests have the highest response rate while email requests have the lowest.",
    "data": [
      {
        "label": "SMS/Text Message",
        "value": 42
      },
      {
        "label": "In-Person Request",
        "value": 35
      },
      {
        "label": "QR Code at Point of Sale",
        "value": 28
      },
      {
        "label": "Mobile App Prompt",
        "value": 24
      },
      {
        "label": "Email Request",
        "value": 18
      }
    ],
    "annotation": "SMS requests generate 2.3x more reviews than email requests.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "local-seo-citation-building-guide": {
    "title": "NAP Inconsistency Impact on Local Rankings",
    "subtitle": "How citation errors affect visibility in local search results",
    "description": "This chart shows the correlation between NAP consistency issues and decreased local search ranking positions, based on 2025 local SEO industry data.",
    "data": [
      {
        "label": "Complete NAP Match",
        "value": 92,
        "detail": "Businesses with perfect NAP consistency"
      },
      {
        "label": "Minor Phone Variations",
        "value": 78,
        "detail": "Slight phone formatting differences"
      },
      {
        "label": "Address Abbreviations",
        "value": 65,
        "detail": "St vs Street, Ave vs Avenue"
      },
      {
        "label": "Business Name Variations",
        "value": 54,
        "detail": "Inc, LLC, or Co. inconsistencies"
      },
      {
        "label": "Major NAP Mismatch",
        "value": 31,
        "detail": "Multiple conflicting details"
      }
    ],
    "annotation": "Perfect NAP consistency correlates with 92% higher local ranking visibility compared to businesses with major inconsistencies.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "local-seo-google-reviews-ranking-factor": {
    "title": "Local SEO Ranking Factors",
    "subtitle": "How Google Reviews Compare to Other Key Elements",
    "description": "This chart shows the relative importance of various ranking factors in Google's local search algorithm, based on 2026 industry studies. Google reviews account for 17% of local pack ranking factors, making them the third most influential element after proximity and relevance.",
    "data": [
      {
        "label": "Proximity to Searcher",
        "value": 28
      },
      {
        "label": "Business Relevance",
        "value": 22
      },
      {
        "label": "Google Reviews",
        "value": 17
      },
      {
        "label": "Website Authority",
        "value": 15
      },
      {
        "label": "Business Information Accuracy",
        "value": 10
      },
      {
        "label": "Social Signals",
        "value": 8
      }
    ],
    "annotation": "Google reviews are the third most important local ranking factor, directly influencing 17% of search visibility.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "multi-location-business-review-management": {
    "title": "Top Review Response Challenges for Multi-Location Brands",
    "subtitle": "Percentage of franchise/chain managers reporting each as a major hurdle",
    "description": "This chart shows the most common challenges multi-location businesses face when managing customer reviews across different locations, based on survey data from franchise and chain store managers.",
    "data": [
      {
        "label": "Inconsistent Brand Voice",
        "value": 78
      },
      {
        "label": "Slow Response Times",
        "value": 65
      },
      {
        "label": "Local SEO Impact",
        "value": 59
      },
      {
        "label": "Staff Training Gaps",
        "value": 52
      },
      {
        "label": "Review Platform Fragmentation",
        "value": 47
      }
    ],
    "annotation": "Inconsistent brand voice is the #1 challenge, affecting 78% of multi-location businesses.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "negative-google-review-management-guide": {
    "title": "Impact of Negative Review Responses",
    "subtitle": "How different response strategies affect customer perception",
    "description": "This chart shows how various response approaches to negative Google reviews influence customer perception and business outcomes, based on industry research and customer behavior studies.",
    "data": [
      {
        "label": "Professional & empathetic response",
        "value": 78,
        "detail": "Customers view business more positively"
      },
      {
        "label": "Generic template response",
        "value": 32,
        "detail": "Limited positive impact on perception"
      },
      {
        "label": "Defensive/argumentative response",
        "value": 15,
        "detail": "Actually worsens customer opinion"
      },
      {
        "label": "No response at all",
        "value": 8,
        "detail": "Customers assume business doesn't care"
      },
      {
        "label": "Offline resolution offered",
        "value": 45,
        "detail": "Negative reviewers become loyal customers"
      }
    ],
    "annotation": "Professional, empathetic responses to negative reviews improve customer perception by 78% and can convert critics into loyal customers.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "qr-code-google-review-collection-guide": {
    "title": "QR Code Review Collection Process",
    "subtitle": "From setup to 5-star review in 4 steps",
    "description": "This flowchart illustrates the complete workflow for implementing a QR code review collection system, showing how businesses can guide customers from initial setup to receiving valuable 5-star reviews.",
    "annotation": "A systematic QR code process can triple review volume in 60 days.",
    "type": "process-flow",
    "steps": [
      {
        "label": "Get Review Link",
        "detail": "Generate your Google review link"
      },
      {
        "label": "Create QR Code",
        "detail": "Design and customize your code"
      },
      {
        "label": "Strategic Placement",
        "detail": "Position where customers see it"
      },
      {
        "label": "Collect Reviews",
        "detail": "Customers scan and leave feedback"
      }
    ]
  },
  "real-estate-agent-review-strategy": {
    "title": "Review Response Impact on Lead Conversion",
    "subtitle": "How different response strategies affect real estate lead generation",
    "description": "This chart shows how different approaches to responding to online reviews impact lead conversion rates for real estate agents. Data is based on industry analysis of 500+ real estate professionals.",
    "data": [
      {
        "label": "Respond to all reviews within 24 hours",
        "value": 42
      },
      {
        "label": "Personalized responses to 4-5 star reviews",
        "value": 28
      },
      {
        "label": "Generic template responses",
        "value": 12
      },
      {
        "label": "Respond only to negative reviews",
        "value": 8
      },
      {
        "label": "No response to any reviews",
        "value": 3
      }
    ],
    "annotation": "Agents who respond to all reviews within 24 hours see 14x more leads than those who don't respond.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "restaurant-google-review-strategy": {
    "title": "90-Day Restaurant Review Growth Strategy",
    "subtitle": "From 10 to 500 Google reviews in 3 months",
    "description": "This visual process flow outlines the step-by-step strategy restaurants can implement over 90 days to systematically grow from 10 to 500 Google reviews, combining in-person engagement, digital follow-up, and reputation management tactics.",
    "annotation": "Consistent multi-channel engagement drives exponential review growth.",
    "type": "process-flow",
    "steps": [
      {
        "label": "Setup & Training",
        "detail": "Train staff, set up QR codes, create email/SMS templates"
      },
      {
        "label": "In-Person Ask",
        "detail": "Staff request reviews at tables, include on receipts"
      },
      {
        "label": "Digital Follow-Up",
        "detail": "Automated email/SMS 2-24 hours after visit"
      },
      {
        "label": "Respond & Monitor",
        "detail": "Daily response to all reviews, track sentiment"
      },
      {
        "label": "Scale & Refine",
        "detail": "Analyze what works, optimize timing/messaging"
      }
    ]
  },
  "retail-store-google-review-strategy": {
    "title": "Review Impact on Retail Purchase Decisions",
    "subtitle": "Percentage of shoppers influenced by different review factors",
    "description": "This chart shows how different aspects of Google reviews influence retail shoppers' purchase decisions, based on survey data from retail consumers. It highlights which review elements small business owners should prioritize when managing their online reputation.",
    "data": [
      {
        "label": "Overall Star Rating",
        "value": 94
      },
      {
        "label": "Recent Reviews (Last 30 Days)",
        "value": 78
      },
      {
        "label": "Review Responses from Business",
        "value": 65
      },
      {
        "label": "Review Quantity (50+ Reviews)",
        "value": 72
      },
      {
        "label": "Detailed Customer Photos",
        "value": 58
      }
    ],
    "annotation": "Star rating is the most influential factor, but recent reviews and business responses significantly impact shopper trust.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "review-analytics-sentiment-analysis-guide": {
    "title": "Top Review Analytics Metrics Impact",
    "subtitle": "How key metrics correlate with business improvement success",
    "description": "This chart shows the five most impactful review analytics metrics for driving operational improvements, based on analysis of businesses that successfully implemented review insights.",
    "data": [
      {
        "label": "Sentiment Polarity Score",
        "value": 92
      },
      {
        "label": "Review Response Rate",
        "value": 88
      },
      {
        "label": "Issue Resolution Tracking",
        "value": 85
      },
      {
        "label": "Competitor Benchmarking",
        "value": 78
      },
      {
        "label": "Review Volume Trends",
        "value": 72
      }
    ],
    "annotation": "Sentiment analysis is the most critical metric for extracting actionable business insights from reviews.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "review-management-checklist-new-business": {
    "title": "90-Day Review Management Process",
    "subtitle": "Step-by-step checklist for new business review success",
    "description": "This flowchart visualizes the essential 90-day review management process for new businesses, showing how to systematically build review volume and quality while maintaining ethical practices.",
    "annotation": "Following this 90-day process helps new businesses build credibility and improve local search rankings.",
    "type": "process-flow",
    "steps": [
      {
        "label": "Claim",
        "detail": "Claim all business profiles (Google, Yelp, etc.)"
      },
      {
        "label": "Seed",
        "detail": "Request 5-10 reviews from known customers"
      },
      {
        "label": "Scale",
        "detail": "Implement QR codes & email/SMS requests"
      },
      {
        "label": "Optimize",
        "detail": "Respond to all reviews & track performance"
      }
    ]
  },
  "review-management-roi-calculator-guide": {
    "title": "Review Management ROI Breakdown",
    "subtitle": "How positive reviews translate to incremental revenue",
    "description": "This waterfall chart visualizes how review management activities create measurable revenue impact, starting with baseline revenue and showing how each review-related factor contributes to total incremental value.",
    "data": [
      {
        "label": "Baseline Revenue",
        "value": 100000,
        "type": "start"
      },
      {
        "label": "Conversion Lift",
        "value": 15000,
        "type": "increase"
      },
      {
        "label": "Higher AOV",
        "value": 8000,
        "type": "increase"
      },
      {
        "label": "Reduced CAC",
        "value": 5000,
        "type": "increase"
      },
      {
        "label": "Review Mgmt Costs",
        "value": -12000,
        "type": "decrease"
      }
    ],
    "totalLabel": "Net Revenue Impact",
    "totalValue": 116000,
    "valueLabel": "$",
    "annotation": "Effective review management generates $16K net revenue impact after costs",
    "type": "waterfall"
  },
  "review-velocity-impact-local-ranking": {
    "title": "Monthly Review Velocity by Industry",
    "subtitle": "Average new reviews needed for competitive local SEO performance",
    "description": "This chart shows the average number of new reviews per month required for businesses in different industries to maintain competitive local SEO rankings, based on industry benchmarks and Google's preference for consistent review velocity.",
    "data": [
      {
        "label": "Restaurants",
        "value": 25
      },
      {
        "label": "Healthcare",
        "value": 15
      },
      {
        "label": "Home Services",
        "value": 12
      },
      {
        "label": "Retail",
        "value": 18
      },
      {
        "label": "Professional Services",
        "value": 8
      }
    ],
    "annotation": "Restaurants need the highest review velocity (25/month) due to frequent customer interactions and high competition.",
    "type": "horizontal-bar",
    "valueLabel": "reviews"
  },
  "salon-spa-review-management-strategy": {
    "title": "Review Rating Impact on Salon Conversions",
    "subtitle": "How star ratings affect client booking decisions",
    "description": "This chart shows the percentage increase in conversion rates for salons and spas at different average star ratings, based on industry data from BrightLocal. Businesses with ratings between 4.0-4.5 stars see significantly higher conversion rates compared to those with lower ratings.",
    "data": [
      {
        "label": "5.0 Stars",
        "value": 25
      },
      {
        "label": "4.5 Stars",
        "value": 17
      },
      {
        "label": "4.0 Stars",
        "value": 12
      },
      {
        "label": "3.5 Stars",
        "value": 0
      },
      {
        "label": "3.0 Stars",
        "value": -8
      }
    ],
    "annotation": "Aim for 4.0+ stars: each 0.5-star increase boosts conversions significantly.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "schema-markup-local-business-seo": {
    "title": "Local Business Schema Implementation Impact",
    "subtitle": "Visibility improvements after implementing structured data",
    "description": "This chart shows the percentage increase in key local SEO metrics for businesses that implement comprehensive schema markup compared to those without structured data.",
    "data": [
      {
        "label": "Local Pack Appearances",
        "value": 42
      },
      {
        "label": "Click-through Rate",
        "value": 35
      },
      {
        "label": "Review Snippet Visibility",
        "value": 58
      },
      {
        "label": "Mobile Search Visibility",
        "value": 31
      },
      {
        "label": "Voice Search Results",
        "value": 47
      }
    ],
    "annotation": "Implementing both core business and review schema delivers the most significant visibility gains.",
    "type": "horizontal-bar",
    "valueLabel": "%"
  },
  "voice-search-local-seo-optimization": {
    "title": "Voice Search vs Text Search Query Length",
    "subtitle": "Average word count per query type (2024 data)",
    "description": "This chart compares the average length of voice search queries versus traditional text search queries, highlighting how voice searches tend to be longer and more conversational.",
    "data": [
      {
        "label": "Voice Search Queries",
        "value": 7.2
      },
      {
        "label": "Text Search Queries",
        "value": 2.8
      },
      {
        "label": "Voice Questions (Who/What/Where)",
        "value": 8.5
      },
      {
        "label": "Text Questions (Who/What/Where)",
        "value": 4.1
      },
      {
        "label": "Voice Local Queries",
        "value": 9.3
      },
      {
        "label": "Text Local Queries",
        "value": 3.6
      }
    ],
    "annotation": "Voice searches are 2-3x longer than text searches, requiring more conversational keyword optimization.",
    "type": "horizontal-bar",
    "valueLabel": "words"
  }
} as Record<string, ChartSpec>;
