/**
 * generate-chart-data.ts
 * Uses DeepSeek API to generate SVG chart data specs for each blog article.
 * Usage: npx tsx scripts/generate-chart-data.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';

dotenv.config({ path: path.join(__dirname, '..', '.env.local') });
const DEEPSEEK_API_KEY = process.env.DEEPSEEK_API_KEY || '';

// Import blog data directly via relative path
import { GENERATED_BLOG_POSTS } from '../src/lib/blog-data-generated';

interface ChartSpec {
  type: 'horizontal-bar' | 'waterfall' | 'process-flow';
  title: string;
  subtitle?: string;
  description: string;
  data?: Array<{ label: string; value: number; color?: string }>;
  steps?: Array<{ label: string; detail?: string }>;
  valueLabel?: string;
  totalLabel?: string;
  totalValue?: number;
  annotation?: string;
}

const SYSTEM_PROMPT = `You are a data visualization expert for SEO/review management articles. Given a blog article, generate ONE chart specification in JSON format.

RULES:
1. Choose the BEST chart type:
   - "horizontal-bar": For comparing metrics, percentages, statistics, rankings. Best for most articles.
   - "waterfall": For showing cumulative costs, ROI breakdowns, step-by-step value accumulation.
   - "process-flow": For showing workflows, step-by-step processes (max 5 steps).

2. The chart must visualize the article's KEY DATA POINT or core concept. Make it insightful.

3. Data must be realistic and grounded in real-world SEO/review management statistics.

4. "description" must be a natural-language summary of the chart (critical for SEO/screen readers).

5. For horizontal-bar: 4-6 data items with numeric values. "valueLabel" can be "%", "x", "K", "$", etc.

6. For waterfall: 3-5 items. Include "totalLabel" and "totalValue".

7. For process-flow: 3-5 steps with short labels (max 15 chars) and optional detail (max 25 chars).

8. Always include "annotation" — one-line key takeaway.

9. Title should be short (max 50 chars). Subtitle optional (max 60 chars).

OUTPUT ONLY VALID JSON. No markdown fences, no explanation.`;

async function generateChart(slug: string, title: string, excerpt: string, category: string, headings: string[]): Promise<ChartSpec | null> {
  const userPrompt = `Article: "${title}"
Category: ${category}
Summary: ${excerpt}
Sections: ${headings.join(' | ')}

Generate a chart JSON spec.`;

  try {
    const res = await fetch('https://api.deepseek.com/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${DEEPSEEK_API_KEY}`,
      },
      body: JSON.stringify({
        model: 'deepseek-chat',
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: userPrompt },
        ],
        temperature: 0.4,
        max_tokens: 1500,
      }),
    });

    if (!res.ok) {
      console.error(`  API ${res.status}: ${await res.text()}`);
      return null;
    }

    const json = await res.json();
    const content = json.choices?.[0]?.message?.content?.trim();
    if (!content) return null;

    const cleaned = content.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
    return JSON.parse(cleaned) as ChartSpec;
  } catch (err) {
    console.error(`  Error:`, (err as Error).message);
    return null;
  }
}

async function main() {
  if (!DEEPSEEK_API_KEY) {
    console.error('Missing DEEPSEEK_API_KEY');
    process.exit(1);
  }

  const articles = GENERATED_BLOG_POSTS;
  console.log(`Found ${articles.length} articles. Generating chart data...\n`);

  const chartData: Record<string, ChartSpec> = {};
  let success = 0;

  for (let i = 0; i < articles.length; i++) {
    const a = articles[i];
    const headings = a.sections.map((s) => s.heading);
    console.log(`[${i + 1}/${articles.length}] ${a.slug}`);

    const spec = await generateChart(a.slug, a.title, a.excerpt, a.category, headings);
    if (spec) {
      chartData[a.slug] = spec;
      success++;
      console.log(`  ✅ ${spec.type} — "${spec.title}"`);
    } else {
      console.log(`  ❌ Failed`);
    }

    // Rate limit
    if (i < articles.length - 1) await new Promise((r) => setTimeout(r, 250));
  }

  // Write output as TypeScript
  const outputPath = path.join(__dirname, '..', 'src', 'lib', 'chart-data.ts');
  const output = `/**
 * Auto-generated chart data for blog articles.
 * Generated by scripts/generate-chart-data.ts via DeepSeek API.
 * DO NOT EDIT MANUALLY.
 */

import type { ChartSpec } from '@/components/ArticleChart';

export const CHART_DATA: Record<string, ChartSpec> = ${JSON.stringify(chartData, null, 2)} as Record<string, ChartSpec>;
`;

  fs.writeFileSync(outputPath, output, 'utf-8');
  console.log(`\n✅ Done! ${success}/${articles.length} charts generated.`);
  console.log(`Output: ${outputPath}`);
}

main().catch(console.error);
